server:
  port: 8080

spring:
  application:
    name: pnc-parcial-final-hotel

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_reservas_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
